version: "3"
services:
  jupytR:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: HousePrices
    image: houseprices
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - "8887:8888"
      - "6007:6006"
    volumes:
      - ./:/home/jovyan/work
    command: /opt/conda/bin/jupyter notebook --ip='0.0.0.0' --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
    environment: 
      - auth.env